"""生成 CentralizedBackup 160个接口的测试用例 Excel"""
import openpyxl
from openpyxl.styles import Font, Alignment, PatternFill, Border, Side

DST = "/Volume1/eee/cb-api-test/CentralizedBackup_API_TestCases.xlsx"

apis = []
cid = 0
def A(m, p, mt, pr, f, t, pre="", st="", ex="", rm=""):
    global cid; cid += 1
    apis.append((f"CB-{cid:03d}", m, p, f, pr, mt, t, pre, st, ex, rm, ""))

# ===== PC/Server (39) =====
M="PC/Server"
A(M,"/win/devices?type={type}","GET","P1","设备管理","按类型查询设备列表","已登录TOS","1. GET type=desktop 2. 检查响应","返回200，code=true，data为设备数组","type: desktop/server")
A(M,"/win/api/device","GET","P1","设备管理","查询所有设备列表","已登录TOS","GET请求检查响应","返回200，data包含device数组")
A(M,"/win/api/device/{device_id}","GET","P2","设备管理","查询指定设备详情","设备已存在","GET传入有效设备ID","返回200，data包含设备详情","不存在时仍返200")
A(M,"/win/api/device/{device_id}","DELETE","P2","设备管理","删除指定设备","设备已存在","DELETE指定设备","返回200，code=true","删除不存在的设备不报错")
A(M,"/win/batch/devices/delete","POST","P2","设备管理","批量删除设备","设备已存在","POST设备ID列表","返回200，批量删除成功")
A(M,"/win/api/device/{device_id}/volume","GET","P2","设备管理","查询设备卷信息","设备已存在","GET设备卷信息","返回200，data包含卷列表")
A(M,"/win/devices/{device_id}/upgrade","PUT","P3","设备管理","升级设备Agent","设备在线","PUT升级请求","返回200","设备离线时可能失败")
A(M,"/win/devices/{device_id}/task","GET","P2","设备管理","查询设备任务摘要","设备已存在","GET摘要","返回200，data包含任务信息")
A(M,"/win/tasks?type={type}","GET","P1","任务管理","按类型查询任务列表","已登录TOS","GET tasks?type=desktop","返回200，data为任务数组","type: desktop/server")
A(M,"/win/api/task","GET","P1","任务管理","查询所有任务列表","已登录TOS","GET全部任务","返回200，data包含tasks数组")
A(M,"/win/api/task/{task_id}","GET","P2","任务管理","查询指定任务详情","任务已存在","GET指定任务ID","返回200，data包含任务详情")
A(M,"/win/api/task/{task_id}/exec","PUT","P1","任务管理","执行备份任务","任务已创建且设备在线","PUT执行请求","返回200，任务变为执行中")
A(M,"/win/api/task/{task_id}/cancel","PUT","P2","任务管理","取消执行中的任务","任务正在执行","PUT取消请求","返回200，任务变为已取消")
A(M,"/win/api/task/{task_id}/verbose","GET","P2","任务管理","查询任务详细执行信息","任务已存在","GET verbose信息","返回200，data包含详细执行日志")
A(M,"/win/api/task/{task_id}","PUT","P2","任务管理","编辑任务配置","任务已存在","PUT修改任务参数","返回200，配置修改成功")
A(M,"/win/tasks/relink?type={type}","GET","P3","任务管理","查询可重连的任务","已登录TOS","GET relink列表","返回200，data包含可重连任务")
A(M,"/win/batch/tasks/add","POST","P2","任务管理","批量添加任务","设备已存在","POST批量任务数据","返回200，批量创建成功")
A(M,"/win/batch/tasks/exec","POST","P2","任务管理","批量执行任务","任务已创建","POST批量执行","返回200，批量任务开始执行")
A(M,"/win/batch/tasks/cancel","POST","P3","任务管理","批量取消任务","任务执行中","POST批量取消","返回200，批量取消成功")
A(M,"/win/batch/tasks/delete","POST","P2","任务管理","批量删除任务","任务已存在","POST批量删除","返回200，批量删除成功")
A(M,"/win/batch/tasks/edit","POST","P3","任务管理","批量编辑任务","任务已存在","POST批量编辑","返回200，批量修改成功")
A(M,"/win/devices/{did}/tasks/{tid}/versions","GET","P1","版本管理","查询任务版本列表","任务已执行备份","GET版本列表","返回200，data包含版本数组")
A(M,"/win/devices/{did}/tasks/{tid}/versions/{vid}","GET","P2","版本管理","查询指定版本详情","版本已存在","GET版本详情","返回200，data包含版本信息")
A(M,"/win/devices/{did}/tasks/{tid}/guide","GET","P3","版本管理","查询版本引导信息","任务已存在","GET引导","返回200，data包含引导数据")
A(M,"/win/devices/{did}/tasks/{tid}/version/{vid}","GET","P2","版本管理","查询版本详细信息","版本已存在","GET版本详细","返回200，data包含版本详细")
A(M,"/win/devices/{did}/tasks/{tid}/versions/{vid}","PUT","P2","版本管理","锁定/解锁版本","版本已存在","PUT锁定状态修改","返回200，锁定状态更新")
A(M,"/win/devices/{did}/tasks/{tid}/versions/{vid}/disks/{dkid}/partitions/{pid}","GET","P3","版本管理","查询版本磁盘分区(5层嵌套路由)","版本和分区已存在","GET磁盘分区详情","返回200，data包含分区信息","5层嵌套路由")
A(M,"/win/api/portal/get_res_task","GET","P1","还原管理","查询还原任务列表","已登录TOS","GET还原任务列表","返回200，data包含还原任务数组")
A(M,"/win/api/portal/create_res_task","POST","P1","还原管理","创建还原任务","已有完成的备份版本","POST创建传入版本和目标","返回200，还原任务创建成功")
A(M,"/win/api/portal/cancel_res?id={id}","GET","P2","还原管理","取消还原任务","还原任务执行中","GET取消","返回200，还原任务已取消")
A(M,"/win/api/portal/delete_res?id={id}","GET","P2","还原管理","删除还原任务","还原任务已存在","GET删除","返回200，还原任务已删除")
A(M,"/win/api/portal/restore","POST","P1","还原管理","执行还原操作","还原任务已创建","POST还原执行","返回200，还原操作已开始")
A(M,"/win/api/portal/browse_image?file_id={fid}","GET","P3","Portal浏览","浏览备份镜像文件","已有备份版本","GET浏览镜像","返回200，data包含文件列表")
A(M,"/win/api/portal/get_dev_dir_sub_dirs?device_uuid={uuid}","GET","P3","Portal浏览","获取设备子目录","设备已存在","GET子目录","返回200，data包含目录信息")
A(M,"/win/portal/dir","GET","P3","Portal浏览","浏览Portal目录","已登录TOS","GET目录","返回200，data包含目录结构")
A(M,"/pc/windows","GET","P2","客户端下载","下载PC客户端","已登录TOS","GET下载","返回200或文件流")
A(M,"/server/windows","GET","P2","客户端下载","下载Server客户端","已登录TOS","GET下载","返回200或文件流")
A(M,"/win/devices/{did}/tasks/{tid}","GET","P2","任务详情","查询设备下任务详情","设备和任务已存在","GET任务详情","返回200，data包含任务详情")
A(M,"/win/devices/{did}/tasks/{tid}/version","GET","P2","版本管理","查询设备任务版本","任务已存在","GET版本列表","返回200，data包含版本信息")

# ===== FileServer (33) =====
M="FileServer"
A(M,"/file/FileServer/device","GET","P1","设备管理","查询文件服务器设备列表","已登录TOS","GET设备列表","返回200，data包含设备数组")
A(M,"/file/FileServer/device/{device_id}","GET","P2","设备管理","查询指定文件服务器设备","设备已存在","GET指定设备","返回200，data包含设备详情")
A(M,"/file/FileServer/device","POST","P1","设备管理","添加文件服务器设备","已登录TOS","POST设备信息(SMB/Rsync)","返回200，设备创建成功")
A(M,"/file/FileServer/device/{device_id}","DELETE","P2","设备管理","删除文件服务器设备","设备已存在","DELETE指定设备","返回200，设备删除成功")
A(M,"/file/FileServer/device/readDir","POST","P2","设备管理","读取文件服务器目录","设备已连接","POST目录路径","返回200，data包含目录内容")
A(M,"/file/FileServer/login","GET","P1","登录管理","查询文件服务器登录列表","已登录TOS","GET登录列表","返回200，data包含登录信息数组")
A(M,"/file/FileServer/login/","POST","P2","登录管理","添加文件服务器登录","设备已存在","POST登录凭据","返回200，登录创建成功")
A(M,"/file/FileServer/login/{login_id}/edit","PUT","P3","登录管理","编辑登录信息","登录已存在","PUT修改登录","返回200，修改成功")
A(M,"/file/FileServer/login_state/{login_id}","GET","P2","登录管理","查询登录连接状态","登录已存在","GET连接状态","返回200，data包含状态")
A(M,"/file/FileServer/backup_task","GET","P1","备份任务","查询备份任务列表","已登录TOS","GET任务列表","返回200，data包含任务数组")
A(M,"/file/FileServer/backup_task/{task_id}","GET","P2","备份任务","查询指定备份任务","任务已存在","GET指定任务","返回200，data包含任务详情")
A(M,"/file/FileServer/backup_task","POST","P1","备份任务","创建备份任务","设备已添加","POST任务配置","返回200，任务创建成功")
A(M,"/file/FileServer/task/{task_id}/edit","PUT","P2","备份任务","编辑备份任务","任务已存在","PUT修改配置","返回200，修改成功")
A(M,"/file/FileServer/task/{task_id}/start","POST","P1","备份任务","启动备份任务","任务已创建","POST启动","返回200，任务开始执行")
A(M,"/file/FileServer/task/{task_id}/stop","POST","P2","备份任务","停止备份任务","任务执行中","POST停止","返回200，任务已停止")
A(M,"/file/FileServer/backup_task/start","POST","P1","备份任务","启动备份(v2)","任务已创建","POST启动备份","返回200，备份开始")
A(M,"/file/FileServer/backup_task/stop","POST","P2","备份任务","停止备份(v2)","备份执行中","POST停止备份","返回200，备份已停止")
A(M,"/file/FileServer/backup_task/import","POST","P3","备份任务","导入备份任务","已登录TOS","POST导入数据","返回200，导入成功")
A(M,"/file/FileServer/task","GET","P2","备份任务","查询任务列表(旧接口)","已登录TOS","GET旧版列表","返回200，data包含任务","兼容旧版")
A(M,"/file/FileServer/task/","GET","P3","备份任务","查询任务列表详情","已登录TOS","GET任务详情","返回200，data包含详情")
A(M,"/file/FileServer/task/{task_id}/start","POST","P1","备份任务","启动任务(旧接口)","任务已创建","POST启动","返回200，任务开始")
A(M,"/file/FileServer/task/{task_id}/stop","POST","P2","备份任务","停止任务(旧接口)","任务执行中","POST停止","返回200，任务已停止")
A(M,"/fileServer/SMB","GET","P3","备份任务","查询SMB信息","已登录TOS","GET SMB配置","返回200，data包含SMB信息")
A(M,"/file/FileServer/backup_task/versions/{task_id}","GET","P1","版本管理","查询备份任务版本列表","任务已执行备份","GET版本列表","返回200，data包含版本数组")
A(M,"/file/FileServer/version/{ver_id}","GET","P2","版本管理","查询指定版本详情","版本已存在","GET版本详情","返回200，data包含版本信息")
A(M,"/file/FileServer/version/delete","POST","P2","版本管理","删除指定版本","版本已存在","POST删除","返回200，版本删除成功")
A(M,"/file/FileServer/version/set_version_locked","POST","P2","版本管理","设置版本锁定状态","版本已存在","POST锁定/解锁","返回200，锁定状态更新")
A(M,"/file/FileServer/backup_task/versions/delete","POST","P2","版本管理","删除备份任务版本","版本已存在","POST删除版本","返回200，删除成功")
A(M,"/file/FileServer/backup_task/versions/lock","POST","P2","版本管理","锁定备份任务版本","版本已存在","POST锁定版本","返回200，锁定成功")
A(M,"/file/FileServer/restore_task","GET","P1","还原管理","查询还原任务列表","已登录TOS","GET还原列表","返回200，data包含还原任务数组")
A(M,"/file/FileServer/restore_task/{task_id}","GET","P2","还原管理","查询指定还原任务","还原任务已存在","GET指定还原","返回200，data包含还原任务详情")
A(M,"/file/FileServer/restore","GET","P1","还原管理","查询还原列表","已登录TOS","GET还原列表","返回200，data包含还原数组")
A(M,"/file/FileServer/restore/{restore_id}","GET","P2","还原管理","查询指定还原详情","还原已存在","GET还原详情","返回200")

# ===== VMware (38) =====
M="VMware"
A(M,"/VMware/vmware/device","GET","P1","设备管理","查询VMware设备列表","已登录TOS","GET设备列表","返回200，data包含设备数组")
A(M,"/VMware/vmware/device?update_status={v}","GET","P2","设备管理","查询设备列表(带状态刷新)","已登录TOS","GET update_status=true","返回200，data包含设备及状态")
A(M,"/VMware/vmware/device/{device_id}","GET","P2","设备管理","查询指定设备详情","设备已存在","GET指定设备","返回200，data包含设备详情")
A(M,"/VMware/vmware/device","POST","P1","设备管理","添加VMware设备","已登录TOS","POST ESXi连接信息","返回200，设备添加成功")
A(M,"/VMware/vmware/device/{device_id}","DELETE","P2","设备管理","删除VMware设备","设备已存在","DELETE指定设备","返回200，设备删除成功")
A(M,"/VMware/vmware/device/check_resource_is_enough","POST","P2","设备管理","检查资源是否充足","设备已存在","POST资源请求","返回200，data包含检查结果")
A(M,"/VMware/vmware/device/check_restore_is_support","POST","P2","设备管理","检查还原是否支持","设备已存在","POST还原检查","返回200，data包含支持状态")
A(M,"/VMware/vmware/device/check_vm_is_exist","POST","P2","设备管理","检查虚拟机是否存在","设备已存在","POST VM信息","返回200，data包含存在状态")
A(M,"/VMware/vmware/device/{device_id}/device_status","GET","P2","设备管理","查询设备连接状态","设备已存在","GET连接状态","返回200，data包含连接状态")
A(M,"/VMware/vmware/device/{device_id}/be_linked_task","GET","P3","设备管理","查询设备被关联的任务","设备已存在","GET关联任务","返回200，data包含关联任务列表")
A(M,"/VMware/vmware/get_task_devices/","GET","P2","设备管理","查询任务关联的设备","已登录TOS","GET任务设备","返回200，data包含设备列表")
A(M,"/VMware/vmware/device/datacenters/{device_id}","GET","P2","数据中心浏览","查询数据中心列表","设备已连接","GET数据中心","返回200，data包含数据中心数组")
A(M,"/VMware/vmware/device/datacenter_clusters","POST","P2","数据中心浏览","查询数据中心集群列表","数据中心已存在","POST数据中心ID","返回200，data包含集群数组")
A(M,"/VMware/vmware/device/datacenter_cluster_hosts","POST","P2","数据中心浏览","查询集群主机列表","集群已存在","POST集群ID","返回200，data包含主机数组")
A(M,"/VMware/vmware/device/datacenter_cluster_host_vms","POST","P2","数据中心浏览","查询主机虚拟机列表","主机已存在","POST主机ID","返回200，data包含虚拟机数组")
A(M,"/VMware/vmware/device/datacenter_folders","POST","P3","数据中心浏览","查询数据中心文件夹列表","数据中心已存在","POST数据中心ID","返回200，data包含文件夹数组")
A(M,"/VMware/vmware/device/datacenter_folder_vms","POST","P3","数据中心浏览","查询文件夹下的虚拟机","文件夹已存在","POST文件夹ID","返回200，data包含虚拟机数组")
A(M,"/VMware/vmware/device/datacenter_datastores","POST","P3","数据中心浏览","查询数据存储列表","数据中心已存在","POST数据中心ID","返回200，data包含数据存储数组")
A(M,"/VMware/vmware/device/datacenter_networks","POST","P3","数据中心浏览","
